### ISSUE TITLE
能不能不要把master的其他文件拷贝到gh-pages分支呢？

### ISSUE THREAD

**Issue by xing393939** [ZanderZhao/gitbook-action#14]
RT，目前是拷贝所有文件到gh-pages分支

**Comment by ZanderZhao** [comment]
不知道我理解的对不对，
+ 可以把master需要build的内容放在一个文件夹内，再在配置里面指定这个文件夹，[可以参考这个](https://github.com/ZanderZhao/gitbook-action/blob/e01972861cb09ea963529c2ddc626a36c0a6cc02/.github/workflows/gitbook-action.yml#L24)
+ 注意，如果有md文件在build文件夹内，但是没有出现在SUMMARY.md文件里面，这种情况通常也是不build的，会当做需要拷贝的资源，如你最近仓库里面的2.md和3.md，而1.md会变为html

**Comment by xing393939** [comment]
这样可以解决问题，谢谢！
