### ISSUE TITLE
请教一下为什么发布的github pages不显示相对路径的图片？

### ISSUE THREAD

**Issue by kuweiguge** [ZanderZhao/gitbook-action#16]
下面是[github项目](https://github.com/kuweiguge/Grokking-Modern-System-Design-Interview-Gitbook)的配置
- [book.json](https://github.com/kuweiguge/Grokking-Modern-System-Design-Interview-Gitbook/blob/master/book.json)
- [gitbook-action.yml](https://github.com/kuweiguge/Grokking-Modern-System-Design-Interview-Gitbook/blob/master/.github/workflows/gitbook-action.yml)
- github pages 发布分支指定的是 `gh-pages`

图片文件在[.gitbook/asserts](https://github.com/kuweiguge/Grokking-Modern-System-Design-Interview-Gitbook/tree/master/.gitbook/assets)文件夹中，在本地md 工具中可以正常显示。

**Comment by ZanderZhao** [comment]
### 原因：
整个流程是这样的，
+ 1. 主分支编写源码
+ 2. gitbook-action把源码编译变成html并放到gh-pages分支
+ 3. github page服务拉取gh-pages分支源码，默认开启jekyll服务，并使用jekyll把.md文件生成html
+ 4. 如果开启jekyll服务，github page服务把jekyll生成的文件部署到github.io服务器，如果没开启jekyll服务，则把gh-pages所有文件放在github.io服务器
+ 5. 我们访问的是github.io服务器

---

### 问题出现在：
+ 默认开启jekyll服务，jekyll编译时会隐藏下划线和点开头的文件，导致部署的实际是没有那个资源文件夹的

---

### 排查方法：
+ 截止你提交issue时，访问这个[图片地址](https://kuweiguge.github.io/Grokking-Modern-System-Design-Interview-Gitbook/.gitbook/assets/Screenshot%202023-09-03%20at%2012.24.49%20AM.png)是空的，甚至其他点开头的文件夹都不行，因为就没部署在github.io服务器上

---

### 解决方法：
+ [这样在源码分支添加一个flag文件.nojekyll](https://github.com/Zander-Dev-Workspace/Grokking-Modern-System-Design-Interview-Gitbook/blob/master/.nojekyll)，
+ [gitbook-action应该会自动拉取这个文件到 gh-pages分支](https://github.com/Zander-Dev-Workspace/Grokking-Modern-System-Design-Interview-Gitbook/blob/gh-pages/.nojekyll)，然后github action 就会拉取gh-pages到github.io服务器，应该就可以了
+ 说明：那个测试repo我没配置密钥，两个分支flag都是我手动添加的，实际上应该只要在源码文件夹添加就可以了，你试试，有问题再追加。

**Comment by kuweiguge** [comment]
完美解决！非常感谢！大佬懂的就是多，我查了一上午 也没能解决。
