### ISSUE TITLE
是否可以传入 npm 命令或者 apt 命令进行一些额外的依赖包安装

### ISSUE THREAD

**Issue by windard** [ZanderZhao/gitbook-action#2]
问题：在生成 PDF 或者 mobi 等电子书的时候，在生成的时候将 svg 转成 png 图片的时候有问题
```
error: error while generating page "README.md": 

Error: Error converting /tmp/tmp-281LPVxSm5Bv6U1/842cb21f.svg into /tmp/tmp-281LPVxSm5Bv6U1/302430b8.png
```

网上搜了一下需要安装指定 `svgexport` 版本，但是 Gitbook 本身的配置文件中是没有无关的版本依赖的，需要在生成之前执行 npm 命令安装

```
npm install svgexport -g
```

希望能够提供这个功能，类似于现在已有的 `font_install` 字段

**Comment by ZanderZhao** [comment]
> 问题：在生成 PDF 或者 mobi 等电子书的时候，在生成的时候将 svg 转成 png 图片的时候有问题
> 
> ```
> error: error while generating page "README.md": 
> 
> Error: Error converting /tmp/tmp-281LPVxSm5Bv6U1/842cb21f.svg into /tmp/tmp-281LPVxSm5Bv6U1/302430b8.png
> ```
> 
> 网上搜了一下需要安装指定 `svgexport` 版本，但是 Gitbook 本身的配置文件中是没有无关的版本依赖的，需要在生成之前执行 npm 命令安装
> 
> ```
> npm install svgexport -g
> ```
> 
> 希望能够提供这个功能，类似于现在已有的 `font_install` 字段

解决：可以试试在`font_install`字段这样写`sudo apt-get install fonts-noto-cjk && npm install svgexport -g` 甚至直接写个脚本，wget然后再执行也可以

**Comment by windard** [comment]
> > 问题：在生成 PDF 或者 mobi 等电子书的时候，在生成的时候将 svg 转成 png 图片的时候有问题
> > ```
> > error: error while generating page "README.md": 
> > 
> > Error: Error converting /tmp/tmp-281LPVxSm5Bv6U1/842cb21f.svg into /tmp/tmp-281LPVxSm5Bv6U1/302430b8.png
> > ```
> > 
> > 
> > 网上搜了一下需要安装指定 `svgexport` 版本，但是 Gitbook 本身的配置文件中是没有无关的版本依赖的，需要在生成之前执行 npm 命令安装
> > ```
> > npm install svgexport -g
> > ```
> > 
> > 
> > 希望能够提供这个功能，类似于现在已有的 `font_install` 字段
> 
> 解决：可以试试在`font_install`字段这样写`sudo apt-get install fonts-noto-cjk && npm install svgexport -g` 甚至直接写个脚本，wget然后再执行也可以

😂，可以是可以，但这样就比较 tricky ，我这里已经 fork 了一份你的代码直接改了。我在想如果你能支持这个参数就更好了。

**Comment by windard** [comment]
https://github.com/ZanderZhao/gitbook-action/pull/3

**Comment by ZanderZhao** [comment]
> #3

已合并修复，thanks

**Comment by windard** [comment]
加个微信，保持联系？MTg2MDc1NzE5MTQ=
