### ISSUE TITLE
Publish sucessfully, But Github pages build fail

### ISSUE THREAD

**Issue by deleyva** [ZanderZhao/gitbook-action#4]
I am having problems getting this action to work and I am stuck trying to figure out what am I doing wrong.

I have the action working on projects like [this](https://github.com/catedu/abies-lectores) but on [this one](https://github.com/catedu/manualdoceo) always says ...

> Your site is having problems building: Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.

The output of the job scheduled by the action does not throw any error. Also, I am able to gitbook serve and build the book locally. I have added also a .nojekyll file, but nothing works.

Thanks for sharing your knowledge and your work.

**Comment by ZanderZhao** [comment]
> I am having problems getting this action to work and I am stuck trying to figure out what am I doing wrong.
> 
> I have the action working on projects like [this](https://github.com/catedu/abies-lectores) but on [this one](https://github.com/catedu/manualdoceo) always says ...
> 
> > Your site is having problems building: Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.
> 
> The output of the job scheduled by the action does not throw any error. Also, I am able to gitbook serve and build the book locally. I have added also a .nojekyll file, but nothing works.
> 
> Thanks for sharing your knowledge and your work.

It has been fixed in v1.2.3, For [Detail error 3201](https://ZanderZhao.github.io/gitbook-action/error.html) please.

**Comment by witnessgpi** [comment]
> > I am having problems getting this action to work and I am stuck trying to figure out what am I doing wrong.
> > I have the action working on projects like [this](https://github.com/catedu/abies-lectores) but on [this one](https://github.com/catedu/manualdoceo) always says ...
> > > Your site is having problems building: Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.
> > 
> > 
> > The output of the job scheduled by the action does not throw any error. Also, I am able to gitbook serve and build the book locally. I have added also a .nojekyll file, but nothing works.
> > Thanks for sharing your knowledge and your work.
> 
> It has been fixed in v1.2.3, For [Detail error 3201](https://ZanderZhao.github.io/gitbook-action/error.html) please.

Thank you so much !!!! Your Error-3201-"How to fix it " have saved my life !!!🤩😍
